import React, { useState, useEffect } from 'react';
import { 
  Shield, Mic, KeyRound, ShieldAlert, BarChart3, 
  Activity, BookOpen, User as UserIcon, Bell, ChevronDown, CheckCircle2,
  LogOut, ShieldCheck, Settings, Sparkles
} from 'lucide-react';
import { DetectionResult, SecurityAlert, UserPersona } from './types';
import { LiveDetectionView } from './components/LiveDetectionView';
import { SecondaryVerificationView } from './components/SecondaryVerificationView';
import { SocAlertsView } from './components/SocAlertsView';
import { AnalyticsView } from './components/AnalyticsView';
import { SystemHealthView, personas } from './components/SystemHealthView';
import { ArchitectureDocsView } from './components/ArchitectureDocsView';
import { ProfileView } from './components/ProfileView';
import { AdminView } from './components/AdminView';
import { AuthScreen } from './components/AuthScreen';
import { useAuth } from './context/AuthContext';

// Initial realistic security incidents generated by the backend
const INITIAL_ALERTS: SecurityAlert[] = [
  {
    id: 'alt-8910',
    sessionId: 'sess-849201',
    severity: 'CRITICAL',
    status: 'NEW',
    title: 'High-Confidence Neural Voice Clone Impersonation Attempt',
    description: 'Acoustic pipeline detected 82% vocoder spectral flatness and anomalous high-frequency diffusion boundary phase jumps on customer support VIP channel.',
    assignedTo: 'analyst@voiceshield.ai',
    riskScore: 88.5,
    classification: 'VOICE_CLONED',
    createdAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    investigationNotes: 'Awaiting secondary voice challenge response verification.'
  },
  {
    id: 'alt-8909',
    sessionId: 'sess-739104',
    severity: 'HIGH',
    status: 'UNDER_INVESTIGATION',
    title: 'Excessive Spectral Flatness with Rigid Pitch Prosody',
    description: 'FastAPI DSP signal analysis flagged zero micro-jitter variance in F0 fundamental frequency, indicative of concatenative TTS playback.',
    assignedTo: 'analyst@voiceshield.ai',
    riskScore: 74.2,
    classification: 'SYNTHETIC',
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    investigationNotes: 'Reviewing audio spectrum FFT bins 128-256 for vocoder harmonics.'
  },
  {
    id: 'alt-8908',
    sessionId: 'sess-619283',
    severity: 'MEDIUM',
    status: 'RESOLVED',
    title: 'Abrupt Frame-to-Frame Temporal Spectral Flux Discontinuity',
    description: 'Moderate boundary jump detected. Speaker successfully completed secondary Telugu phonetic challenge phrase.',
    assignedTo: 'admin@voiceshield.ai',
    actionTaken: 'Secondary Challenge Passed (Score 91%). Authorized session.',
    riskScore: 48.0,
    classification: 'SUSPICIOUS',
    createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    investigationNotes: 'Legitimate user in noisy acoustic background.'
  }
];

const INITIAL_HISTORY: DetectionResult[] = [
  {
    id: 'det-101',
    sessionId: 'sess-849201',
    classification: 'VOICE_CLONED',
    modelConfidence: 0.96,
    securityRiskScore: 88.5,
    threatLevel: 'CRITICAL',
    aiGeneratedProbability: 0.94,
    voiceCloneProbability: 0.92,
    speakerSimilarityScore: 0.84,
    recommendedAction: 'TERMINATE_SESSION_AND_ALERT_SOC',
    isDevelopmentResult: true,
    developmentWarning: 'Active: DevelopmentModelAdapter physical DSP acoustic pipeline.',
    explanationSummary: 'Acoustic analysis computed risk score 88.5/100 (CRITICAL threat). Neural vocoder spectral flatness and diffusion boundary anomalies verified.',
    inferenceDurationMs: 34,
    modelVersion: 'v1.0.0-dev',
    signals: [
      {
        signalType: 'spectral_flatness_vocoder_artifact',
        anomalyDetected: true,
        rawMetricValue: 0.412,
        weightPercentage: 30,
        contributionScore: 24.7,
        explanation: 'Elevated spectral flatness across higher octaves characteristic of neural vocoder artifacts.'
      },
      {
        signalType: 'pitch_prosodic_stability_variance',
        anomalyDetected: true,
        rawMetricValue: 4.8,
        weightPercentage: 25,
        contributionScore: 22.5,
        explanation: 'Atypical pitch prosody with lack of organic human micro-jitter.'
      },
      {
        signalType: 'temporal_phase_spectral_flux',
        anomalyDetected: true,
        rawMetricValue: 0.092,
        weightPercentage: 20,
        contributionScore: 16.0,
        explanation: 'Spectral flux indicates frame-to-frame phase splicing discontinuities.'
      },
      {
        signalType: 'acoustic_bandwidth_codec_rolloff',
        anomalyDetected: true,
        rawMetricValue: 0.038,
        weightPercentage: 15,
        contributionScore: 10.5,
        explanation: 'Acoustic frequency spectrum exhibits neural codec band-limiting.'
      },
      {
        signalType: 'zero_crossing_fricative_consistency',
        anomalyDetected: false,
        rawMetricValue: 0.142,
        weightPercentage: 10,
        contributionScore: 1.0,
        explanation: 'Unvoiced consonant and voiced transitions within normal boundary.'
      }
    ],
    timestamp: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    channelType: 'MICROPHONE_STREAM'
  },
  {
    id: 'det-102',
    sessionId: 'sess-739104',
    classification: 'SYNTHETIC',
    modelConfidence: 0.92,
    securityRiskScore: 74.2,
    threatLevel: 'HIGH',
    aiGeneratedProbability: 0.88,
    voiceCloneProbability: 0.65,
    recommendedAction: 'TRIGGER_CHALLENGE_RESPONSE_MFA',
    isDevelopmentResult: true,
    developmentWarning: 'Active: DevelopmentModelAdapter physical DSP acoustic pipeline.',
    explanationSummary: 'Acoustic analysis computed risk score 74.2/100 (HIGH threat). Unnatural harmonic structure detected.',
    inferenceDurationMs: 41,
    modelVersion: 'v1.0.0-dev',
    signals: [],
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    channelType: 'AUDIO_UPLOAD'
  },
  {
    id: 'det-103',
    sessionId: 'sess-619283',
    classification: 'HUMAN',
    modelConfidence: 0.97,
    securityRiskScore: 14.8,
    threatLevel: 'LOW',
    aiGeneratedProbability: 0.08,
    voiceCloneProbability: 0.04,
    recommendedAction: 'ALLOW_SESSION_CONTINUE',
    isDevelopmentResult: true,
    developmentWarning: 'Active: DevelopmentModelAdapter physical DSP acoustic pipeline.',
    explanationSummary: 'Acoustic analysis computed risk score 14.8/100 (LOW threat). Natural vocal cord harmonics verified.',
    inferenceDurationMs: 29,
    modelVersion: 'v1.0.0-dev',
    signals: [],
    timestamp: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    channelType: 'MICROPHONE_STREAM'
  }
];

export function App() {
  const { user, loading, logout } = useAuth();

  type TabType = 'detection' | 'verification' | 'alerts' | 'analytics' | 'health' | 'docs' | 'profile' | 'admin';
  const [activeTab, setActiveTab] = useState<TabType>('detection');
  const [currentPersona, setCurrentPersona] = useState<UserPersona>(personas[1]);
  const [alerts, setAlerts] = useState<SecurityAlert[]>(INITIAL_ALERTS);
  const [history, setHistory] = useState<DetectionResult[]>(INITIAL_HISTORY);
  const [latestResult, setLatestResult] = useState<DetectionResult | null>(INITIAL_HISTORY[0]);
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  // Sync role-based initial view when user logs in
  useEffect(() => {
    if (user) {
      if (user.accountRole === 'ADMIN') {
        setActiveTab('admin');
      } else if (user.accountRole === 'ANALYST') {
        setActiveTab('alerts');
      } else {
        setActiveTab('detection');
      }
    }
  }, [user?.uid, user?.accountRole]);

  const showToast = (msg: string) => {
    setToastMessage(msg);
    setTimeout(() => setToastMessage(null), 4000);
  };

  const handleNewDetection = (result: DetectionResult) => {
    setLatestResult(result);
    setHistory((prev) => [result, ...prev]);

    if (result.threatLevel === 'HIGH' || result.threatLevel === 'CRITICAL') {
      const newAlert: SecurityAlert = {
        id: 'alt-' + Math.random().toString(36).substring(2, 7),
        sessionId: result.sessionId,
        severity: result.threatLevel,
        status: 'NEW',
        title: result.threatLevel === 'CRITICAL' ? 'Critical Voice Impersonation Detected' : 'Elevated Acoustic Spoofing Anomaly',
        description: result.explanationSummary,
        assignedTo: user?.email || 'analyst@voiceshield.ai',
        riskScore: result.securityRiskScore,
        classification: result.classification,
        createdAt: new Date().toISOString()
      };
      setAlerts((prev) => [newAlert, ...prev]);
      showToast(`🚨 Incident Logged: ${result.threatLevel} threat detected (${result.securityRiskScore.toFixed(1)}/100)`);
    } else {
      showToast(`✅ Acoustic Verification Complete: Score ${result.securityRiskScore.toFixed(1)}/100 (${result.threatLevel})`);
    }
  };

  const handleUpdateAlert = (id: string, updates: Partial<SecurityAlert>) => {
    setAlerts((prev) => prev.map((a) => (a.id === id ? { ...a, ...updates } : a)));
    showToast(`Investigation updated for incident ${id}`);
  };

  // If session is still loading
  if (loading) {
    return (
      <div className="min-h-screen bg-[#09090b] text-zinc-100 flex flex-col items-center justify-center">
        <div className="w-12 h-12 bg-blue-600 rounded-xl text-white font-bold flex items-center justify-center text-lg shadow-xl shadow-blue-600/30 animate-pulse mb-4">
          VS
        </div>
        <p className="text-xs font-mono text-zinc-400">Initializing VoiceShield AI session...</p>
      </div>
    );
  }

  // Section 2: If unauthenticated, show professional Auth landing screen
  if (!user) {
    return <AuthScreen />;
  }

  const criticalAlertCount = alerts.filter((a) => a.status === 'NEW' && (a.severity === 'CRITICAL' || a.severity === 'HIGH')).length;

  const getRoleBadgeStyle = (role: string) => {
    switch (role) {
      case 'ADMIN':
        return 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30';
      case 'ANALYST':
        return 'bg-amber-500/10 text-amber-400 border-amber-500/30';
      default:
        return 'bg-blue-500/10 text-blue-400 border-blue-500/30';
    }
  };

  return (
    <div className="min-h-screen bg-[#09090b] text-zinc-100 flex flex-col font-sans selection:bg-blue-500/20 selection:text-blue-400">
      {/* Top Header with Status Indicators & Session */}
      <header className="h-16 border-b border-zinc-800 bg-[#0c0c0e] sticky top-0 z-50 px-4 sm:px-6 flex items-center justify-between">
        <div className="flex items-center gap-6">
          {/* Logo & Brand matching Sleek Interface */}
          <div 
            onClick={() => setActiveTab(user.accountRole === 'ADMIN' ? 'admin' : user.accountRole === 'ANALYST' ? 'alerts' : 'detection')}
            className="flex items-center gap-3 cursor-pointer">
            <div className="w-8 h-8 bg-blue-600 rounded flex items-center justify-center font-bold text-white shadow-md shadow-blue-600/20 text-sm">
              VS
            </div>
            <div>
              <h1 className="font-bold text-sm tracking-tight text-white flex items-center gap-2">
                VOICE SHIELD <span className="text-blue-500 text-[10px] font-mono">AI v4.2.0</span>
              </h1>
              <div className="text-[10px] text-zinc-500 uppercase tracking-widest font-mono">Impersonation Defense</div>
            </div>
          </div>

          {/* Microservice Health Indicators from Sleek design */}
          <div className="hidden lg:flex items-center gap-6 border-l border-zinc-800 pl-6">
            <div className="flex items-center gap-2">
              <span className="text-[10px] text-zinc-500 uppercase font-mono">AI Service</span>
              <span className="w-2 h-2 rounded-full bg-emerald-500 shadow-sm shadow-emerald-500/50"></span>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-[10px] text-zinc-500 uppercase font-mono">PostgreSQL</span>
              <span className="w-2 h-2 rounded-full bg-emerald-500 shadow-sm shadow-emerald-500/50"></span>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-[10px] text-zinc-500 uppercase font-mono">Redis</span>
              <span className="w-2 h-2 rounded-full bg-emerald-500 shadow-sm shadow-emerald-500/50"></span>
            </div>
          </div>
        </div>

        {/* Right Header: Profile, Role badge & Sign Out */}
        <div className="flex items-center gap-3">
          <div className="hidden xl:flex bg-zinc-900 px-3 py-1 rounded text-xs font-mono border border-zinc-800 text-zinc-400">
            SESSION: {latestResult ? latestResult.sessionId : 'VS-8821-X'}
          </div>

          {/* User Profile Pill */}
          <button
            id="btn-header-profile"
            onClick={() => setActiveTab('profile')}
            className={`flex items-center gap-2.5 px-2.5 py-1 rounded-lg border transition ${
              activeTab === 'profile'
                ? 'bg-zinc-800 border-zinc-700 text-white'
                : 'bg-zinc-900 border-zinc-800 text-zinc-300 hover:border-zinc-700'
            }`}>
            {user.photoURL ? (
              <img
                src={user.photoURL}
                alt={user.fullName}
                referrerPolicy="no-referrer"
                className="w-6 h-6 rounded-full object-cover border border-zinc-700"
              />
            ) : (
              <div className="w-6 h-6 rounded-full bg-zinc-800 flex items-center justify-center font-mono text-[10px] font-bold text-blue-400">
                {user.fullName.substring(0, 2).toUpperCase()}
              </div>
            )}
            <div className="text-left hidden sm:block">
              <span className="text-xs font-semibold block leading-tight truncate max-w-[120px]">
                {user.fullName}
              </span>
            </div>
            <span className={`px-1.5 py-0.2 rounded text-[9px] font-mono font-bold border ${getRoleBadgeStyle(user.accountRole)}`}>
              {user.accountRole}
            </span>
          </button>

          {/* Sign Out Button */}
          <button
            id="btn-logout"
            onClick={logout}
            title="Sign out of VoiceShield"
            className="p-2 bg-zinc-900 hover:bg-zinc-800 text-zinc-400 hover:text-red-400 rounded-lg border border-zinc-800 transition flex items-center gap-1.5 text-xs">
            <LogOut className="w-3.5 h-3.5" />
            <span className="hidden md:inline text-[11px] font-semibold">Sign Out</span>
          </button>
        </div>
      </header>

      {/* Sub-nav Bar matching Sleek Navigation Theme */}
      <div className="border-b border-zinc-800 bg-[#0c0c0e]/95 backdrop-blur-sm px-4 sm:px-6 py-2.5 flex items-center justify-between overflow-x-auto">
        <nav className="flex items-center gap-1.5 sm:gap-2 text-xs">
          {/* Admin Tab (Admin Only) */}
          {user.accountRole === 'ADMIN' && (
            <button
              id="nav-admin"
              onClick={() => setActiveTab('admin')}
              className={`px-3 py-2 rounded-lg transition flex items-center gap-2 cursor-pointer ${
                activeTab === 'admin' 
                  ? 'bg-blue-600 text-white font-semibold shadow-sm' 
                  : 'text-zinc-400 hover:text-zinc-200 hover:bg-zinc-800/30'
              }`}>
              <Settings className="w-3.5 h-3.5" />
              <span>Admin Console</span>
            </button>
          )}

          {/* Live Detection (All roles) */}
          <button
            id="nav-detection"
            onClick={() => setActiveTab('detection')}
            className={`px-3 py-2 rounded-lg transition flex items-center gap-2 cursor-pointer ${
              activeTab === 'detection' 
                ? 'bg-zinc-800/80 text-white font-semibold border border-zinc-700/50 shadow-inner' 
                : 'text-zinc-400 hover:text-zinc-200 hover:bg-zinc-800/30'
            }`}>
            {activeTab === 'detection' && <div className="w-2 h-2 bg-blue-500 rounded-full animate-pulse" />}
            <Mic className="w-3.5 h-3.5 text-blue-400" />
            <span>Live Detection</span>
          </button>

          {/* Challenge Verification (All roles) */}
          <button
            id="nav-verification"
            onClick={() => setActiveTab('verification')}
            className={`px-3 py-2 rounded-lg transition flex items-center gap-2 cursor-pointer ${
              activeTab === 'verification' 
                ? 'bg-zinc-800/80 text-white font-semibold border border-zinc-700/50 shadow-inner' 
                : 'text-zinc-400 hover:text-zinc-200 hover:bg-zinc-800/30'
            }`}>
            {activeTab === 'verification' && <div className="w-2 h-2 bg-blue-500 rounded-full animate-pulse" />}
            <KeyRound className="w-3.5 h-3.5 text-blue-400" />
            <span>Challenge Verification</span>
          </button>

          {/* SOC Alerts (Analyst & Admin) */}
          {(user.accountRole === 'ANALYST' || user.accountRole === 'ADMIN') && (
            <button
              id="nav-alerts"
              onClick={() => setActiveTab('alerts')}
              className={`px-3 py-2 rounded-lg transition flex items-center gap-2 cursor-pointer relative ${
                activeTab === 'alerts' 
                  ? 'bg-zinc-800/80 text-white font-semibold border border-zinc-700/50 shadow-inner' 
                  : 'text-zinc-400 hover:text-zinc-200 hover:bg-zinc-800/30'
              }`}>
              {activeTab === 'alerts' && <div className="w-2 h-2 bg-blue-500 rounded-full animate-pulse" />}
              <ShieldAlert className="w-3.5 h-3.5 text-red-400" />
              <span>SOC Alerts</span>
              {criticalAlertCount > 0 && (
                <span className="px-1.5 py-0.2 rounded-full bg-red-600 text-white text-[10px] font-mono font-bold animate-pulse">
                  {criticalAlertCount}
                </span>
              )}
            </button>
          )}

          {/* Detection History / Analytics (All roles) */}
          <button
            id="nav-analytics"
            onClick={() => setActiveTab('analytics')}
            className={`px-3 py-2 rounded-lg transition flex items-center gap-2 cursor-pointer ${
              activeTab === 'analytics' 
                ? 'bg-zinc-800/80 text-white font-semibold border border-zinc-700/50 shadow-inner' 
                : 'text-zinc-400 hover:text-zinc-200 hover:bg-zinc-800/30'
            }`}>
            {activeTab === 'analytics' && <div className="w-2 h-2 bg-blue-500 rounded-full animate-pulse" />}
            <BarChart3 className="w-3.5 h-3.5 text-blue-400" />
            <span>Detection History</span>
          </button>

          {/* System Health (Analyst & Admin) */}
          {(user.accountRole === 'ANALYST' || user.accountRole === 'ADMIN') && (
            <button
              id="nav-health"
              onClick={() => setActiveTab('health')}
              className={`px-3 py-2 rounded-lg transition flex items-center gap-2 cursor-pointer ${
                activeTab === 'health' 
                  ? 'bg-zinc-800/80 text-white font-semibold border border-zinc-700/50 shadow-inner' 
                  : 'text-zinc-400 hover:text-zinc-200 hover:bg-zinc-800/30'
              }`}>
              {activeTab === 'health' && <div className="w-2 h-2 bg-blue-500 rounded-full animate-pulse" />}
              <Activity className="w-3.5 h-3.5 text-emerald-400" />
              <span>System Health</span>
            </button>
          )}

          {/* Architecture Specs (Analyst & Admin) */}
          {(user.accountRole === 'ANALYST' || user.accountRole === 'ADMIN') && (
            <button
              id="nav-docs"
              onClick={() => setActiveTab('docs')}
              className={`px-3 py-2 rounded-lg transition flex items-center gap-2 cursor-pointer ${
                activeTab === 'docs' 
                  ? 'bg-zinc-800/80 text-white font-semibold border border-zinc-700/50 shadow-inner' 
                  : 'text-zinc-400 hover:text-zinc-200 hover:bg-zinc-800/30'
              }`}>
              {activeTab === 'docs' && <div className="w-2 h-2 bg-blue-500 rounded-full animate-pulse" />}
              <BookOpen className="w-3.5 h-3.5 text-zinc-400" />
              <span>Architecture Specs</span>
            </button>
          )}

          {/* Profile Tab */}
          <button
            id="nav-profile"
            onClick={() => setActiveTab('profile')}
            className={`px-3 py-2 rounded-lg transition flex items-center gap-2 cursor-pointer ${
              activeTab === 'profile' 
                ? 'bg-zinc-800/80 text-white font-semibold border border-zinc-700/50 shadow-inner' 
                : 'text-zinc-400 hover:text-zinc-200 hover:bg-zinc-800/30'
            }`}>
            {activeTab === 'profile' && <div className="w-2 h-2 bg-blue-500 rounded-full animate-pulse" />}
            <UserIcon className="w-3.5 h-3.5 text-blue-400" />
            <span>Profile</span>
          </button>
        </nav>

        <div className="hidden md:flex items-center gap-3 text-xs font-mono">
          <span className="text-[10px] text-zinc-500 uppercase">Latency:</span>
          <span className="text-zinc-200 font-bold">142ms</span>
          <span className="text-blue-500 text-[10px]">DSP-DSP</span>
        </div>
      </div>

      {/* Toast Notification Banner */}
      {toastMessage && (
        <div className="fixed bottom-6 right-6 z-50 bg-[#111114] border border-blue-500/40 text-white px-4 py-3 rounded-xl shadow-2xl flex items-center gap-3 animate-in fade-in slide-in-from-bottom-4 duration-200">
          <CheckCircle2 className="w-5 h-5 text-blue-400 shrink-0" />
          <span className="text-xs font-medium text-zinc-200">{toastMessage}</span>
        </div>
      )}

      {/* Main Content Body */}
      <main className="flex-1 max-w-7xl w-full mx-auto p-4 sm:p-6 md:p-8">
        {activeTab === 'admin' && user.accountRole === 'ADMIN' && <AdminView />}
        {activeTab === 'profile' && <ProfileView />}
        {activeTab === 'detection' && (
          <LiveDetectionView onNewDetection={handleNewDetection} latestResult={latestResult} />
        )}
        {activeTab === 'verification' && <SecondaryVerificationView />}
        {activeTab === 'alerts' && <SocAlertsView alerts={alerts} onUpdateAlert={handleUpdateAlert} />}
        {activeTab === 'analytics' && <AnalyticsView history={history} />}
        {activeTab === 'health' && (
          <SystemHealthView currentPersona={currentPersona} onSwitchPersona={setCurrentPersona} />
        )}
        {activeTab === 'docs' && <ArchitectureDocsView />}
      </main>

      {/* Footer */}
      <footer className="border-t border-zinc-800 bg-[#09090b] py-4 px-6 text-xs text-zinc-500">
        <div className="max-w-7xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-2 font-mono text-[11px]">
          <span>VOICE SHIELD AI v4.2.0 • Real-Time Voice Impersonation Defense</span>
          <span className="text-zinc-600">INPUT: WebAudio API / Stereo / 44.1kHz • Zero Raw Audio Storage</span>
        </div>
      </footer>
    </div>
  );
}

export default App;
